AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  Test:
    Type: String
    Default: Default
  Test2:
    Type: String
    Default: Default

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: test_function.lambda_handler
      CodeUri: test/
      Runtime: python2.7
      Policies:
        Statement:
          - Action:
              - 'codepipeline:*'
              - 'logs:*'
            Effect: Allow
            Resource: '*'
      AutoPublishAlias: shiftit
      DeploymentPreference:
        Enabled: true
        Type: CodeDeployDefault.LambdaAllAtOnce

Outputs:
  TestFunction:
    Description: Test lambda function name
    Value: !Ref TestFunction
    Export:
      Name: TestFunction
  Test: 
    Description: Check the param
    Value: !Ref Test
    Export:
      Name: Checking123
  Test2: 
    Description: Check the param
    Value: !Ref Test2
    Export:
      Name: CheckingNEXTVAL    
